"""empty message

Revision ID: 0b8c4455a806
Revises: 334a1444cec4
Create Date: 2022-01-22 21:43:47.155035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8c4455a806'
down_revision = '334a1444cec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_discount', sa.Column('dish_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_discount', 'tb_dish', ['dish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_discount', type_='foreignkey')
    op.drop_column('tb_discount', 'dish_id')
    # ### end Alembic commands ###
