"""empty message

Revision ID: 334a1444cec4
Revises: fc550cf1c9a3
Create Date: 2022-01-22 21:43:26.104799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334a1444cec4'
down_revision = 'fc550cf1c9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_discount_dish_id_fkey', 'tb_discount', type_='foreignkey')
    op.drop_column('tb_discount', 'dish_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_discount', sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tb_discount_dish_id_fkey', 'tb_discount', 'tb_dish', ['dish_id'], ['id'])
    # ### end Alembic commands ###
