"""empty message

Revision ID: 99636d780c76
Revises: 61e1fde597f3
Create Date: 2022-01-19 21:49:08.118639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99636d780c76'
down_revision = '61e1fde597f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_dish_discount_id_fkey', 'tb_dish', type_='foreignkey')
    op.drop_column('tb_dish', 'discount_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_dish', sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tb_dish_discount_id_fkey', 'tb_dish', 'tb_discount', ['discount_id'], ['id'])
    # ### end Alembic commands ###
