"""empty message

Revision ID: fc550cf1c9a3
Revises: 7beccd47c4a3
Create Date: 2022-01-22 21:42:25.421607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc550cf1c9a3'
down_revision = '7beccd47c4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_discount', sa.Column('dish_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_discount', 'tb_dish', ['dish_id'], ['id'])
    op.drop_constraint('tb_dish_discount_id_fkey', 'tb_dish', type_='foreignkey')
    op.drop_column('tb_dish', 'discount_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_dish', sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tb_dish_discount_id_fkey', 'tb_dish', 'tb_discount', ['discount_id'], ['id'])
    op.drop_constraint(None, 'tb_discount', type_='foreignkey')
    op.drop_column('tb_discount', 'dish_id')
    # ### end Alembic commands ###
