"""empty message

Revision ID: 1abf401f5cdc
Revises: 6aefb48e2452
Create Date: 2021-03-10 16:34:58.611404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abf401f5cdc'
down_revision = '6aefb48e2452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_time123', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_time123')
    # ### end Alembic commands ###
