"""add relations

Revision ID: 1cac6ffbcdb6
Revises: d270bd122985
Create Date: 2021-01-14 19:15:49.454934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cac6ffbcdb6'
down_revision = 'd270bd122985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_dish_tag',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['tb_dish.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tb_tag.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'tag_id')
    )
    op.create_table('rs_user_tag',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tb_tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_table('rs_dish_order',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['tb_dish.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['tb_order.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rs_dish_order')
    op.drop_table('rs_user_tag')
    op.drop_table('rs_dish_tag')
    # ### end Alembic commands ###
