"""empty message

Revision ID: 2fb408e9f32c
Revises: 89b3ab14f1e6
Create Date: 2021-03-10 16:38:55.445635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb408e9f32c'
down_revision = '89b3ab14f1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_time')
    op.drop_column('address', 'update_time')
    # ### end Alembic commands ###
