"""empty message

Revision ID: 35ba975ee233
Revises: e3a26a4c29ac
Create Date: 2021-03-10 16:01:41.846159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ba975ee233'
down_revision = 'e3a26a4c29ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rate', sa.Enum('good', 'ok', 'bad', name='rate_enum'), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('user', 'admin', name='role_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('comment', 'rate')
    # ### end Alembic commands ###
