"""empty message

Revision ID: 366b862f9d6f
Revises: 79e3e9061c1a
Create Date: 2021-01-18 11:52:25.719269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366b862f9d6f'
down_revision = '79e3e9061c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_name_key', 'dish', type_='unique')
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.create_unique_constraint('dish_name_key', 'dish', ['name'])
    # ### end Alembic commands ###
