"""empty message

Revision ID: 39316ffecdd3
Revises: 086220d1896a
Create Date: 2021-03-10 16:33:37.533313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39316ffecdd3'
down_revision = '086220d1896a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_time12', sa.DateTime(), nullable=True))
    op.drop_column('user', 'update_time1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_time1', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'update_time12')
    # ### end Alembic commands ###
