"""empty message

Revision ID: 5ac65b39ed6b
Revises: fea6be4c19ba
Create Date: 2021-03-24 15:47:09.779589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac65b39ed6b'
down_revision = 'fea6be4c19ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('dish_amount', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'dish_amount')
    # ### end Alembic commands ###
