"""empty message

Revision ID: 6434c3e4b22a
Revises: 35ba975ee233
Create Date: 2021-03-10 16:03:32.617428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6434c3e4b22a'
down_revision = '35ba975ee233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_time123', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_time123')
    # ### end Alembic commands ###
