"""empty message

Revision ID: 6adbd03e99af
Revises: 2fb408e9f32c
Create Date: 2021-03-11 09:23:56.632096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6adbd03e99af'
down_revision = '2fb408e9f32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'is_delete')
    op.alter_column('tag', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.add_column('address', sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
