"""empty message

Revision ID: 74106931b794
Revises: 5ec20bffd8a6
Create Date: 2021-03-24 18:27:37.578540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74106931b794'
down_revision = '5ec20bffd8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rate', sa.Enum('good', 'ok', 'bad', name='rate_enum'), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('user', 'admin', name='role_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('comment', 'rate')
    # ### end Alembic commands ###
