"""empty message

Revision ID: 78f4a410e1e2
Revises: 366b862f9d6f
Create Date: 2021-01-19 15:08:04.877879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78f4a410e1e2'
down_revision = '366b862f9d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dish', sa.Column('discount_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dish', 'discount', ['discount_id'], ['id'])
    op.drop_column('dish', 'discount')
    op.drop_column('dish', 'discount_type')
    op.drop_column('user', 'is_vip')
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_vip', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dish', sa.Column('discount_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dish', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.drop_column('dish', 'discount_id')
    op.drop_table('account')
    op.drop_table('discount')
    # ### end Alembic commands ###
