"""empty message

Revision ID: 79e3e9061c1a
Revises: 7afbac305b40
Create Date: 2021-01-18 11:48:11.648967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e3e9061c1a'
down_revision = '7afbac305b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dish', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish', type_='unique')
    # ### end Alembic commands ###
