"""empty message

Revision ID: 8d31b9a964e8
Revises: 4ac6cf3d3876
Create Date: 2021-03-09 21:43:41.669825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d31b9a964e8'
down_revision = '4ac6cf3d3876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rate', sa.Enum('good', 'ok', 'bad', name='rate_enum'), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('user', 'admin', name='role_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('comment', 'rate')
    # ### end Alembic commands ###
