"""empty message

Revision ID: af10ad7227c4
Revises: 6adbd03e99af
Create Date: 2021-03-11 10:36:42.808149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af10ad7227c4'
down_revision = '6adbd03e99af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishimg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_index', sa.Boolean(), nullable=True),
    sa.Column('uri', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('discount', sa.Column('description', sa.String(length=200), nullable=False))
    op.alter_column('discount', 'discount_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discount', 'discount_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('discount', 'description')
    op.drop_table('dishimg')
    # ### end Alembic commands ###
