"""empty message

Revision ID: c505829170f9
Revises: 09e4d40c3b05
Create Date: 2021-03-09 13:43:28.116151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c505829170f9'
down_revision = '09e4d40c3b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.drop_column('user', 'update_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('address', 'is_default')
    # ### end Alembic commands ###
