"""add dish and tag and relation

Revision ID: cd859213b85f
Revises: b3c7674e2db5
Create Date: 2021-01-14 17:01:43.713721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd859213b85f'
down_revision = 'b3c7674e2db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_address', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('tb_address', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('tb_address', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.alter_column('tb_address', 'location',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('tb_address', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('tb_address', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.add_column('tb_user', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'update_time')
    op.alter_column('tb_address', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('tb_address', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('tb_address', 'location',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_column('tb_address', 'update_time')
    op.drop_column('tb_address', 'is_delete')
    op.drop_column('tb_address', 'create_time')
    # ### end Alembic commands ###
