"""empty message

Revision ID: dd931b47e48a
Revises: af10ad7227c4
Create Date: 2021-03-11 10:46:06.425792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd931b47e48a'
down_revision = 'af10ad7227c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishimg', sa.Column('dish_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dishimg', 'dish', ['dish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishimg', type_='foreignkey')
    op.drop_column('dishimg', 'dish_id')
    # ### end Alembic commands ###
