"""empty message

Revision ID: f63c468a0b11
Revises: dd931b47e48a
Create Date: 2021-03-11 10:56:28.324340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63c468a0b11'
down_revision = 'dd931b47e48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('discount1', sa.Float(), nullable=True))
    op.drop_column('discount', 'discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('discount', 'discount1')
    # ### end Alembic commands ###
