"""empty message

Revision ID: fea6be4c19ba
Revises: f63c468a0b11
Create Date: 2021-03-11 10:56:41.460607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fea6be4c19ba'
down_revision = 'f63c468a0b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('discount', sa.Float(), nullable=True))
    op.drop_column('discount', 'discount1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('discount1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('discount', 'discount')
    # ### end Alembic commands ###
